### ISSUE TITLE
Session closes after user gets redirected from another site.

### ISSUE THREAD

**Issue by ghost** [kartikk221/hyper-express-session#10]
I have a setup where the user goes to /core/discord/login and the referral in query strings gets saved in sessions then gets redirected to discord oauth2

After user gets redirected to callback path, the session destroys itself.

I suppose this is because the user got redirected from another site.
Any way to fix this?

**Comment by kartikk221** [comment]
Hello, from what is sounds like, you seem to be encountering a CORS. Cookies don't really play well with cross domain. I would take the following steps to debug your problem:
- Check your database to see If a record for the session gets created.
- Instead of redirecting, simply send a normal response and in chrome see If the cookie gets persisted on the browser.

If the above two work fine, then try out the redirect again but this time track the requests in the chrome dev tools network tab and see If the session cookie has a yellow warning sign next to it. If it has the warning sign next to it or doesn't get saved at all, then that means Chrome is rejecting the cookie and not storing it cross domain.

I would assume a work around for this problem could be where instead of using `Response.redirect()` you can simply render an HTML page which contains the following script to see If this can persist the cookie on the website, so when the user comes back the cookie is available.
```html
<script>location.href = 'REDIRECT_LINK_HERE';</script>
```

**Comment by ghost** [comment]
Turns out that it was an issue with my session configuration.
I had sameSite set to strict, I changed it to lax and it worked.

Thank you for the help ❤️
